package com.app.core;

public enum Color {
	// enum consists of self typed constants
	/*
	 * Code generated by javac
	 * fields : public static final Color WHITE,BLACK,....RED
	 * static  {
	 *   WHITE=new Color("WHITE",0); ---> private ctor ---> super(nm,pos) : java.lang.Enum
	 *   ....
	 *   RED=new Color("RED",4);
	 *   Name the methods generated by javac 
	 *   public static Color[] values()
	 *   public static Color valueOf(String name)
	 *   sop(Color.BLACK,compareTo(Color.RED)); // -1 : based upon ordinal pos.
	 * }
	 */
	WHITE, BLACK, GREY, SILVER, RED;
//	@Override
//	public String toString()
//	{
//		return name().toLowerCase();
//	}
}


